---
# tasks file for django

- name: Instalando Python e Pip
  yum:
    name: python2-pip.noarch
    state: latest
  register: python_pip
  become: True

- name: Instalando VirtualEnv via pip
  pip:
    name: virtualenv
    state: latest
  when: python_pip is succeeded
  become: True
  register: install_virtualenv

- name: Apagando diretório env e mysite caso exista
  command: rm -rf env mysite
  ignore_errors: yes

- name: Criando env
  command: virtualenv env
  args:
    creates: env/bin/activate
  register: create_env

- name: Agora vai 
  shell: source env/bin/activate && \
    pip install djangocms-installer ; \
    djangocms mysite && \
    cd mysite; nohup python manage.py runserver &